sudo: required
services:
- docker

before_install:
- docker pull dpollet/texlive:pillar

script: |
  docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar bash -c "\
    wget --quiet --output-document=- 'https://raw.githubusercontent.com/pillar-markup/pillar/master/download.sh' | bash \
    && make spiralbook "

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-Geographical
  skip_cleanup: true
  user: ducasse
  key:
    secure: m2SSzxZzVS5g1Osdz8MXhVHb0KCTei/krwqTt91GMAKhF/6336MqizlnQH5BDBxFTTU5yD75y0hMdJVWFm4mZl/+uN9gwx5o48oGOvvrr6WKWzzM3xcxPyUiVvxTBErJ8rxr3jPL4xKyi0GcDPPc48NyQUwBurXMxyOFC/4yLLUVZy4VRjD6pbp3eSznc9fa2y0iRsWO9vmK8VJLcH/Udu3xgi6EYmh3U0Ah2tBfSG8laH6BH/KE+WMcxprZ14dP29NBW4uv21xCAPugVlJkFwCs27m9Ybw9+XTogYH1hkIrvXRz4DkQY6S55eajDLd+eY/BqDFH5+3CXKjujhycX3fpRXGvM9QHMwlLwdrEmus1Fh/Lc1d/MX+sQY+8VHSLeCUQKQzVIPtOHdkoCUDhbu7CCNUOEFclLO38fO+aZlPpBJx7KDHbQOfIgYQHT+szyzJ1mv+ViVOv5gZ0lXzbJDZrQP8LfRMtz/Azzbq4gr+VS7SE74YhkvyfGfXybroNE+M8NhZdn76oetQzgy8QcdJqoaKQzNbUCmVlxtenwPCKPBz6mZ1fvTBsEdwDNA3xKtq3j6TxPNPpVJy0n+uYWoKURl22pCEkShdwrcBFgEC9kMYdiMubetO87ahmAJi/yeztz6F3gwjbO+2AaOgOFLJfwc4NtqqbQxYx8sp3y6Y=
